version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy-test

permissions:
  - object: /home/ubuntu/deploy-test
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
